/**
 * Channels exposed by the sandboxed Electron preload bridge.
 *
 * Keep this list transport-only: request and response shapes remain owned by
 * TaskManagerApi and the focused shared contracts it references.
 */
export const IPC_INVOKE_CHANNELS = [
  'agent:cancelRun',
  'agent:continueRun',
  'agent:discoverRuntimeModels',
  'agent:readProtocolMessage',
  'agent:respondToInteraction',
  'agent:retryRun',
  'agent:runtimeCatalog',
  'agent:startReview',
  'agent:startRun',
  'agent:steerRun',
  'agent:syncGoal',
  'agent:updateNativeSession',
  'artifact:read',
  'attachment:clipboard:readImage',
  'attachment:draft:discard',
  'attachment:read',
  'attachment:stage-batch',
  'board:create',
  'board:delete',
  'board:update',
  'discourse:context:pin',
  'discourse:context:preview',
  'discourse:conversation:archive',
  'discourse:conversation:create',
  'discourse:conversation:delete',
  'discourse:conversation:get',
  'discourse:conversation:read',
  'discourse:conversation:rename',
  'discourse:conversations:list',
  'discourse:draft:delete',
  'discourse:draft:get',
  'discourse:draft:save',
  'discourse:drafts:list',
  'discourse:mentions:get',
  'discourse:message:append',
  'discourse:message:cancel-response',
  'discourse:message:get-by-client-id',
  'discourse:message:resume',
  'discourse:message:send',
  'discourse:message:tombstone',
  'discourse:messages:list',
  'discourse:wave:confirm-context',
  'discourse:wave:stop',
  'evidence:refresh',
  'git:deliveryCommit',
  'github:createPullRequest',
  'github:preflight',
  'github:publish',
  'github:refresh',
  'openTarget:execute',
  'openTarget:inspect',
  'preview:approve',
  'preview:binding:delete',
  'preview:binding:set',
  'preview:log:read',
  'preview:open',
  'preview:private:delete',
  'preview:private:import',
  'preview:private:retryCleanup',
  'preview:private:set',
  'preview:recipe-generation:accept',
  'preview:recipe-generation:discard',
  'preview:recipe-generation:generate',
  'preview:recipe-generation:get',
  'preview:recipe-generation:validate',
  'preview:resetData',
  'preview:resolve',
  'preview:retrySetup',
  'preview:start',
  'preview:stop',
  'prompt:refine',
  'repository:add',
  'repository:chooseFolder',
  'repository:disconnect',
  'repository:impact',
  'repository:reconnect',
  'repository:refresh',
  'settings:get',
  'settings:tools:status',
  'settings:tools:test',
  'settings:update',
  'task:create',
  'task:delete',
  'task:list',
  'task:transition',
  'worktree:prepare'
] as const;

export type IpcInvokeChannel = (typeof IPC_INVOKE_CHANNELS)[number];

export const IPC_UPDATE_CHANNEL = 'app:update' as const;
export const IPC_WINDOW_CHROME_CHANNEL = 'windowChrome:sync' as const;
