import fs from 'node:fs/promises';
import path from 'node:path';
import type {
  Repository,
  RepositoryPreflight,
  Task,
  WorktreeRecord,
  WorktreeStatus
} from '../../shared/contracts';
import {
  enforcePosixMode,
  isOwnedByCurrentUser
} from '../filesystem/secureFilesystem';
import { git, gitSucceeds } from '../git/gitCli';

export interface WorktreeSpec {
  branchName: string;
  worktreePath: string;
  baseRef?: string;
  baseSha: string;
}

export interface ParsedGitWorktree {
  path: string;
  headSha?: string;
  branch?: string;
  bare: boolean;
  detached: boolean;
  locked?: string;
  prunable?: string;
}

export class WorktreeService {
  private readonly rootDir: string;

  constructor(rootDir: string) {
    this.rootDir = path.resolve(rootDir);
  }

  getRootDir(): string {
    return this.rootDir;
  }

  buildSpec(task: Task, preflight: RepositoryPreflight): WorktreeSpec {
    if (preflight.status !== 'VALID' || !preflight.headSha) {
      throw new Error(preflight.error ?? 'Repository preflight must pass before creating a worktree.');
    }

    return this.buildSpecFromBase(task, {
      baseRef: preflight.branch,
      baseSha: preflight.headSha
    });
  }

  buildSpecFromBase(
    task: Task,
    base: { baseRef?: string; baseSha: string }
  ): WorktreeSpec {
    const branchName = `task-monki/task-${task.id.slice(0, 8)}-${slugify(task.title)}`;
    return {
      branchName,
      worktreePath: path.join(this.rootDir, task.id),
      baseRef: base.baseRef,
      baseSha: base.baseSha
    };
  }

  async create(record: WorktreeRecord, repositoryPath: string): Promise<WorktreeRecord> {
    await this.ensureOwnedRoot();
    await this.assertOwnedRecordPath(record);

    if (await pathExists(record.worktreePath)) {
      return this.verify(record, repositoryPath);
    }

    const branchExists = await gitSucceeds(repositoryPath, [
      'show-ref',
      '--verify',
      '--quiet',
      `refs/heads/${record.branchName}`
    ]);

    if (branchExists) {
      await git(repositoryPath, ['worktree', 'add', record.worktreePath, record.branchName], 60_000);
    } else {
      await git(
        repositoryPath,
        ['worktree', 'add', '-b', record.branchName, record.worktreePath, record.baseSha],
        60_000
      );
    }

    await enforcePosixMode(record.worktreePath, 0o700);
    return this.verify(record, repositoryPath);
  }

  async verify(record: WorktreeRecord, repositoryPath: string): Promise<WorktreeRecord> {
    await this.ensureOwnedRoot();
    await this.assertOwnedRecordPath(record);
    const parsed = await listGitWorktrees(repositoryPath);
    const expectedPath = await canonicalPath(record.worktreePath);
    const resolved = await Promise.all(
      parsed.map(async (candidate) => ({
        candidate,
        canonical: await canonicalPath(candidate.path)
      }))
    );
    const match = resolved.find((candidate) => candidate.canonical === expectedPath)?.candidate;
    if (!match) {
      return {
        ...record,
        status: 'MISSING',
        error: 'Worktree is not present in git worktree list.',
        updatedAt: new Date().toISOString(),
        lastVerifiedAt: new Date().toISOString()
      };
    }

    return {
      ...record,
      status: statusForParsedWorktree(match),
      headSha: match.headSha,
      error: undefined,
      updatedAt: new Date().toISOString(),
      lastVerifiedAt: new Date().toISOString()
    };
  }

  async remove(record: WorktreeRecord, repositoryPath: string): Promise<WorktreeRecord> {
    await this.ensureOwnedRoot();
    await this.assertOwnedRecordPath(record);
    repositoryPath = await canonicalPath(repositoryPath);
    const worktreePath = await canonicalPath(record.worktreePath);
    if (repositoryPath === worktreePath) {
      throw new Error('Task Monki will not remove the original repository checkout.');
    }

    const verified = await this.verify(record, repositoryPath);
    if (verified.status === 'MISSING') {
      return {
        ...verified,
        status: 'REMOVED',
        error: undefined,
        updatedAt: new Date().toISOString(),
        lastVerifiedAt: new Date().toISOString()
      };
    }
    if (verified.status === 'LOCKED') {
      throw new Error('The local worktree is locked and cannot be removed by Task Monki.');
    }
    if (await hasUncommittedWork(record.worktreePath)) {
      throw new Error(
        'The local worktree has uncommitted or untracked files. Commit, stash, or clean it before removing the worktree.'
      );
    }

    await git(repositoryPath, ['worktree', 'remove', record.worktreePath], 60_000);
    return {
      ...verified,
      status: 'REMOVED',
      error: undefined,
      updatedAt: new Date().toISOString(),
      lastVerifiedAt: new Date().toISOString()
    };
  }

  /**
   * Explicit deletion path for a marker-validated managed Design repository.
   * Unlike normal task removal, this path may remove dirty generated bytes.
   */
  async removeOwnedManaged(
    record: WorktreeRecord,
    repository: Pick<Repository, 'kind' | 'path'>
  ): Promise<WorktreeRecord> {
    if (repository.kind !== 'DESIGN_MANAGED') {
      throw new Error('Forced worktree removal is limited to managed Design repositories.');
    }
    await this.ensureOwnedRoot();
    await this.assertOwnedRecordPath(record);
    if (!samePath(record.worktreePath, path.join(this.rootDir, record.taskId))) {
      throw new Error('Managed Design worktree path does not match its task.');
    }
    const repositoryPath = await canonicalPath(repository.path);
    const worktreePath = await canonicalPath(record.worktreePath);
    if (samePath(repositoryPath, worktreePath)) {
      throw new Error('Task Monki will not remove the original repository checkout.');
    }
    const verified = await this.verify(record, repositoryPath);
    if (verified.status === 'MISSING') {
      if (await pathExists(record.worktreePath)) {
        throw new Error('Unregistered content remains at the managed worktree path.');
      }
      return {
        ...verified,
        status: 'REMOVED',
        error: undefined,
        updatedAt: new Date().toISOString(),
        lastVerifiedAt: new Date().toISOString()
      };
    }
    await git(
      repositoryPath,
      ['worktree', 'remove', '--force', record.worktreePath],
      60_000
    );
    if (await pathExists(record.worktreePath)) {
      throw new Error('Git did not remove the managed Design worktree.');
    }
    return {
      ...verified,
      status: 'REMOVED',
      error: undefined,
      updatedAt: new Date().toISOString(),
      lastVerifiedAt: new Date().toISOString()
    };
  }

  private async ensureOwnedRoot(): Promise<void> {
    await fs.mkdir(this.rootDir, { recursive: true, mode: 0o700 });
    const stat = await fs.lstat(this.rootDir);
    if (!stat.isDirectory() || stat.isSymbolicLink() || !isOwnedByCurrentUser(stat)) {
      throw new Error('Task Monki worktree root failed its ownership check.');
    }
    await enforcePosixMode(this.rootDir, 0o700);
  }

  private async assertOwnedRecordPath(record: WorktreeRecord): Promise<void> {
    if (
      !record.taskId ||
      path.basename(record.taskId) !== record.taskId ||
      record.taskId === '.' ||
      record.taskId === '..' ||
      !samePath(path.dirname(path.resolve(record.worktreePath)), this.rootDir)
    ) {
      throw new Error('Task worktree path escaped its configured root.');
    }
    const stat = await fs.lstat(record.worktreePath).catch((error: NodeJS.ErrnoException) => {
      if (error.code === 'ENOENT') return undefined;
      throw error;
    });
    if (
      stat &&
      (!stat.isDirectory() || stat.isSymbolicLink() || !isOwnedByCurrentUser(stat))
    ) {
      throw new Error('Task worktree path failed its ownership check.');
    }
  }
}

export async function listGitWorktrees(repositoryPath: string): Promise<ParsedGitWorktree[]> {
  const output = await git(repositoryPath, ['worktree', 'list', '--porcelain', '-z']);
  return parseGitWorktreeList(output);
}

export function parseGitWorktreeList(output: string): ParsedGitWorktree[] {
  const records: ParsedGitWorktree[] = [];
  let current: ParsedGitWorktree | undefined;

  for (const field of output.split('\0')) {
    if (!field) {
      if (current) {
        records.push(current);
        current = undefined;
      }
      continue;
    }

    const [key, ...rest] = field.split(' ');
    const value = rest.join(' ');

    if (key === 'worktree') {
      if (current) {
        records.push(current);
      }
      current = {
        path: value,
        bare: false,
        detached: false
      };
      continue;
    }

    if (!current) {
      continue;
    }

    if (key === 'HEAD') {
      current.headSha = value;
    } else if (key === 'branch') {
      current.branch = value.replace(/^refs\/heads\//, '');
    } else if (key === 'bare') {
      current.bare = true;
    } else if (key === 'detached') {
      current.detached = true;
    } else if (key === 'locked') {
      current.locked = value || 'locked';
    } else if (key === 'prunable') {
      current.prunable = value || 'prunable';
    }
  }

  if (current) {
    records.push(current);
  }

  return records;
}

function statusForParsedWorktree(parsed: ParsedGitWorktree): WorktreeStatus {
  if (parsed.locked) {
    return 'LOCKED';
  }
  if (parsed.prunable) {
    return 'PRUNABLE';
  }
  return 'PRESENT';
}

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'task'
  );
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function hasUncommittedWork(worktreePath: string): Promise<boolean> {
  const status = await git(worktreePath, ['status', '--porcelain', '-z']);
  return status.length > 0;
}

async function canonicalPath(filePath: string): Promise<string> {
  try {
    return await fs.realpath(filePath);
  } catch {
    return path.resolve(filePath);
  }
}

function samePath(left: string, right: string): boolean {
  return process.platform === 'win32'
    ? path.resolve(left).toLowerCase() === path.resolve(right).toLowerCase()
    : path.resolve(left) === path.resolve(right);
}
